apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: test-argo
spec:
  project: default

  source:
    repoURL: https://github.com/Rajesh-Sangepu/argocd-task.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: test-argo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
