apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app
  namespace: test-argo
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-progressing.slack: ssd-deployments
    notifications.argoproj.io/subscribe.on-rollout-healthy.slack: ssd-deployments
    notifications.argoproj.io/subscribe.on-rollout-degraded.slack: ssd-deployments
    notifications.argoproj.io/subscribe.on-rollout-degraded.email: rajesh.sangepu@opsmx.io
spec:
  replicas: 4

  selector:
    matchLabels:
      app: my-app

  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx:1.25.3   # âœ… FIXED IMAGE
        ports:
        - containerPort: 80

  strategy:
    canary:
      canaryService: my-app-canary
      stableService: my-app-stable

      steps:
      - setWeight: 25
      - analysis:
          templates:
          - templateName: canary-smoke-test

      - setWeight: 50
      - analysis:
          templates:
          - templateName: canary-smoke-test

      - setWeight: 100
