apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app
  namespace: test-argo
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-progressing.slack: ssd-deployments
    notifications.argoproj.io/subscribe.on-rollout-healthy.slack: ssd-deployments
    notifications.argoproj.io/subscribe.on-rollout-degraded.slack: ssd-deployments
    notifications.argoproj.io/subscribe.on-rollout-degraded.email: rajesh.sangepu@opsmx.io  
spec:
  replicas: 3

  selector:
    matchLabels:
      app: my-app

  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: nginx:1.25.3       # ✅ use a specific tag instead of 'latest'
          ports:
            - containerPort: 80
          readinessProbe:             # ✅ ensures pod is ready before traffic
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 2
            failureThreshold: 3

  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 30 }
        - setWeight: 50
        - pause: { duration: 30 }
        - setWeight: 100
